AWSTemplateFormatVersion: 2010-09-09
Description: Alese Michael / Udacity - This template for both EC2 and securityGroup
Resources:
    myWebAccessSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: This creates a security group for the instance
            GroupName: myWebAccessSecurityGroup
    myWebServerInstance:
        Type: AWS::EC2::Instance
        Properties:
            InstanceType: t3.micro
            ImageId: ami-0022f774911c1d690
            NetworkInterfaces: AssociatePublicIpAddress
            SecurityGroups: myWebAccessSecurityGroup
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash
                    sudo yum update -y
                    sudo yum install -y httpd
                    sudo systemctl start httpd
                    sudo systemctl enable httpd
            SubnetId: subnet-0dbf672659acc44fa
            
